# Generated by Django 5.2 on 2025-05-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emotionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
