# Generated by Django 5.1.6 on 2025-03-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('health_tip', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
