# Generated by Django 5.1.6 on 2025-03-26 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionresult',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='emotion',
            field=models.CharField(max_length=100),
        ),
    ]
