# Generated by Django 5.2 on 2025-05-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_emotionresult_user'),
    ]

    operations = [
    ]
