# Generated by Django 5.2 on 2025-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_fix_emotionresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionresult',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
